insert into authors (id, first_name, last_name) values (1, 'Rayner', 'Debrick');
insert into authors (id, first_name, last_name) values (2, 'Shellie', 'Goody');
insert into authors (id, first_name, last_name) values (3, 'Federico', 'Rippingall');
insert into authors (id, first_name, last_name) values (4, 'Viva', 'Zmitruk');
insert into authors (id, first_name, last_name) values (5, 'Kale', 'Ambridge');
insert into authors (id, first_name, last_name) values (6, 'Alexa', 'Gammack');
insert into authors (id, first_name, last_name) values (7, 'Lise', 'Easterfield');
insert into authors (id, first_name, last_name) values (8, 'Rebecka', 'Trahar');
insert into authors (id, first_name, last_name) values (9, 'Liv', 'Greenhowe');
insert into authors (id, first_name, last_name) values (10, 'Shaylynn', 'Ceyssen');
insert into authors (id, first_name, last_name) values (11, 'Redd', 'Eldrett');
insert into authors (id, first_name, last_name) values (12, 'Lane', 'Mundall');
insert into authors (id, first_name, last_name) values (13, 'Doretta', 'Jerrems');
insert into authors (id, first_name, last_name) values (14, 'Vita', 'Ducker');
insert into authors (id, first_name, last_name) values (15, 'Gwen', 'Bentzen');
insert into authors (id, first_name, last_name) values (16, 'Eyde', 'Titterell');
insert into authors (id, first_name, last_name) values (17, 'Bevin', 'Boam');
insert into authors (id, first_name, last_name) values (18, 'Odelinda', 'Dobrovolski');
insert into authors (id, first_name, last_name) values (19, 'Kristen', 'Picardo');
insert into authors (id, first_name, last_name) values (20, 'Breena', 'Poser');
insert into authors (id, first_name, last_name) values (21, 'Ellyn', 'Baswall');

insert into books (id, price, price_old, title, author_id) values (1, 1805, 1200, 'Stringtough', 1);
insert into books (id, price, price_old, title, author_id) values (2, 1290, 2831, 'Wrapsafe', 2);
insert into books (id, price, price_old, title, author_id) values (3, 2987, 3899, 'Holdlamis', 3);
insert into books (id, price, price_old, title, author_id) values (4, 1474, 2251, 'Subin', 4);
insert into books (id, price, price_old, title, author_id) values (5, 721, 2134, 'Fix San', 5);
insert into books (id, price, price_old, title, author_id) values (6, 2334, 3625, 'Daltfresh', 6);
insert into books (id, price, price_old, title, author_id) values (7, 2448, 2229, 'Konklux', 7);
insert into books (id, price, price_old, title, author_id) values (8, 1350, 3852, 'Alphazap', 8);
insert into books (id, price, price_old, title, author_id) values (9, 2004, 3066, 'Pannier', 9);
insert into books (id, price, price_old, title, author_id) values (10, 1744, 3521, 'Daltfresh', 10);
insert into books (id, price, price_old, title, author_id) values (11, 1779, 3242, 'Opela', 11);
insert into books (id, price, price_old, title, author_id) values (12, 1840, 2229, 'Hatity', 12);
insert into books (id, price, price_old, title, author_id) values (13, 1865, 2136, 'Home Ing', 13);
insert into books (id, price, price_old, title, author_id) values (14, 1370, 2670, 'Transcof', 14);
insert into books (id, price, price_old, title, author_id) values (15, 1468, 3134, 'Domainer', 15);
insert into books (id, price, price_old, title, author_id) values (16, 2346, 1241, 'Subin', 16);
insert into books (id, price, price_old, title, author_id) values (17, 2359, 1266, 'Latlux', 17);
insert into books (id, price, price_old, title, author_id) values (18, 794, 2047, 'Viva', 18);
insert into books (id, price, price_old, title, author_id) values (19, 2443, 2361, 'Tin', 19);
insert into books (id, price, price_old, title, author_id) values (20, 1896, 3940, 'Stim', 20);
insert into books (id, price, price_old, title, author_id) values (21, 2705, 3407, 'Konklab', 21);