DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS author;


CREATE TABLE author
(
    author_id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(250) NOT NULL
);


CREATE TABLE books
(
    book_id INT AUTO_INCREMENT PRIMARY KEY,
    title     VARCHAR(250) NOT NULL,
    priceOld  VARCHAR(250) DEFAULT NULL,
    price     VARCHAR(250) DEFAULT NULL,
    FOREIGN KEY (book_id) REFERENCES author(author_id)
);